export enum Subjects {
    ProductCreated = "product:created",
    ProductUpdated = "product:updated",
    ProductIntegrationCreated = "product:integration:created",
    ProductStockCreated = "product:stock:created",
    ProductStockUpdated = "product:stock:updated",
    CombinationCreated = "combination:created",
    CombinationUpdated = "combination:updated",
    PackageProductLinkCreated = "package:product:link:created",
    PackageProductLinkUpdated = "package:product:link:updated",
    RelationProductLinkCreated = "relation:product:link:created",
    RelationProductLinkUpdated = "relation:product:link:updated",
    UserCreated = "user:created",
    UserUpdated = "user:updated",
    StockCreated = "stock:created",
    StockUpdated = "stock:updated",
    OrderCreated = "order:created",
    OrderUpdated = "order:updated",
    OrderStatusUpdated = "order:status:updated",
    IntegrationCommand = "integration:command",
    IntegrationCommandResult = "integration:command:result",
    EntityDeleted = "entity:deleted",
    ImportImagesFromUrls = 'cdn:import-images-from-urls',
    ImportImagesFromUrlsCompleted = 'cdn:import-images-from-urls-completed',
    DeleteProductImages = 'cdn:delete-product-images',
    DeleteProductImagesCompleted = 'cdn:delete-product-images-completed'
}
